### ISSUE TITLE
how to login into the mail container

### ISSUE THREAD

**Issue by sidealice** [ONLYOFFICE/Docker-MailServer#1]
could you share the server's ssh account

**Comment by AnaMih** [comment]
To login to mail container follow the steps:
- login to machine with docker
- "docker ps" command should show the list with docker containers
- "docker attach" command with mail container id or name " this allows you to attach to a running mail container.

**Comment by sidealice** [comment]
thanks but i didn't get the response use attach command.
I use nscenter to login into the container at last, wisht this would helpful for others who want to get into the container.

**Comment by AnaMih** [comment]
I regret to inform you that there is currently no way to contribute to the project. You only can fork a repo at the moment. We are planning to add the contributing file soon.

**Comment by sidealice** [comment]
thanks and understand.
