### ISSUE TITLE
"Could not resolve host 'xxx.com."

### ISSUE THREAD

**Issue by sidealice** [ONLYOFFICE/Docker-MailServer#2]
Should I add dns information to docker's /etc/default/docker file ?

**Comment by sidealice** [comment]
i would add more details for the issue:

i install 3 dockers, and after i login into the mail server i enabled the log for the postfix, wish following log would helpful for the problem:

Jun 25 13:29:17 jorigin postfix/smtpd[8606]: connect from unknown[180.154.192.222]
Jun 25 13:29:17 jorigin postfix/trivial-rewrite[8608]: warning: do not list domain abc.com.cn in BOTH mydestination and virtual_mailbox_domains
Jun 25 13:29:17 jorigin postfix/smtpd[8606]: 502B3C67A: client=unknown[180.154.192.222]
Jun 25 13:29:17 jorigin postfix/cleanup[8614]: 502B3C67A: message-id=<>
Jun 25 13:29:17 jorigin postfix/qmgr[7927]: 502B3C67A: from=gongyuan.mao@abc.com.cn, size=696, nrcpt=1 (queue active)
Jun 25 13:29:17 jorigin postfix/smtpd[8606]: disconnect from unknown[180.154.192.222]
Jun 25 13:29:21 jorigin postfix/smtpd[8626]: connect from localhost[127.0.0.1]
Jun 25 13:29:22 jorigin postfix/trivial-rewrite[8608]: warning: do not list domain abc.com.cn in BOTH mydestination and virtual_mailbox_domains
Jun 25 13:29:22 jorigin postfix/trivial-rewrite[8608]: warning: do not list domain abc.com.cn in BOTH mydestination and virtual_mailbox_domains
Jun 25 13:29:22 jorigin postfix/smtpd[8626]: 05977C670: client=localhost[127.0.0.1]
Jun 25 13:29:22 jorigin postfix/cleanup[8614]: 05977C670: message-id=20150625132922.05977C670@abc.com.cn
Jun 25 13:29:22 jorigin opendkim[1684]: 05977C670: DKIM-Signature field added (s=dkim, d=abc.com.cn)
Jun 25 13:29:22 jorigin postfix/smtpd[8626]: disconnect from localhost[127.0.0.1]
Jun 25 13:29:22 jorigin postfix/qmgr[7927]: 05977C670: from=gongyuan.mao@abc.com.cn, size=1419, nrcpt=1 (queue active)
Jun 25 13:29:22 jorigin postfix/trivial-rewrite[8608]: warning: do not list domain abc.com.cn in BOTH mydestination and virtual_mailbox_domains
Jun 25 13:29:22 jorigin amavis[2834]: (02834-03) Passed CLEAN {RelayedInternal}, MYUSERS LOCAL [180.154.192.222]:43886 [180.154.192.222] gongyuan.mao@abc.com.cn -> gongyuan.mao@abc.com.cn, Queue-ID: 502B3C67A, mail_id: wKeK8Qhcir3L, Hits: 2.387, size: 661, queued_as: 05977C670, 4443 ms
Jun 25 13:29:22 jorigin postfix/smtp[8620]: 502B3C67A: to=gongyuan.mao@abc.com.cn, relay=127.0.0.1[127.0.0.1]:10024, delay=5, delays=0.46/0.01/0/4.5, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 05977C670)
Jun 25 13:29:22 jorigin postfix/qmgr[7927]: 502B3C67A: removed
Jun 25 13:29:22 jorigin postfix/pipe[8628]: 05977C670: to=gongyuan.mao@abc.com.cn, relay=dovecot, delay=0.33, delays=0.05/0.01/0/0.27, dsn=2.0.0, status=sent (delivered via dovecot service)
Jun 25 13:29:22 jorigin postfix/qmgr[7927]: 05977C670: removed

**Comment by AnaMih** [comment]
Please, specify the commands that you use for Onlyoffice installation.

**Comment by sidealice** [comment]
For Mailserver:
sudo docker run --privileged -i -t -d -p 25:25 -p 143:143 -p 587:587 \
-v /opt/onlyoffice/Mail/Logs:/var/log  \
-v /opt/onlyoffice/Mail/MySQL:/var/lib/mysql  \
-v /opt/onlyoffice/Mail/VMail:/var/vmail  \
-v /opt/onlyoffice/Mail/MailServer:/etc/pki/tls/mailserver \
-h abc.com \
--name onlyoffice-mail-server  \
onlyoffice/mailserver

For Document server i use the way as default. 

For CommunityServer
sudo docker run -i -t -d -p 81:80 \
-v /opt/onlyoffice/Logs:/var/log/onlyoffice  \
-v /opt/onlyoffice/Data:/var/www/onlyoffice/Data  \
-v /opt/onlyoffice/MySQL:/var/lib/mysql  onlyoffice/communityserver
sudo docker run -i -t -d -p 81:80 -p 5222:5222 -p 443:443 \ 
-v /opt/onlyoffice/Logs:/var/log/onlyoffice  \
-v /opt/onlyoffice/Data:/var/www/onlyoffice/Data  \
-v /opt/onlyoffice/MySQL:/var/lib/mysql  \
--link onlyoffice-mail-server:mail_server \
--link onlyoffice-document-server:document_server \
onlyoffice/communityserver

**Comment by AnaMih** [comment]
Domain should be valid and have properly configured DNS 
If you run three containers, two of them (mail and documents) should be linked to the community server:
sudo docker run -i -t -d -p 80:80 -p 5222:5222 -p 443:443 \ 
-v /opt/onlyoffice/Logs:/var/log/onlyoffice \
-v /opt/onlyoffice/Data:/var/www/onlyoffice/Data \
-v /opt/onlyoffice/MySQL:/var/lib/mysql \
--link onlyoffice-mail-server:mail_server \
--link onlyoffice-document-server:document_server \
onlyoffice/communityserver

We'd recommend to turn off the postfix during installation and running onlyoffice mail server as they both use 25 port
