### ISSUE TITLE
Error trying to pull repository

### ISSUE THREAD

**Issue by kot154** [ONLYOFFICE/Docker-MailServer#3]
docker run --privileged -i -t -d -p 25:25 -p 143:143 -p 587:587 -h yourdomain.com onlyoffice/mailserver

```
Error: Status 503 trying to pull repository onlyoffice/mailserver: "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n\n"
```

**Comment by AnaMih** [comment]
Please, specify the Docker version. Onlyoffice products need Docker version 1.4.1 and later https://docs.docker.com/installation/

**Comment by kot154** [comment]
Docker version 1.8.2, build 0a8c2e3
