### ISSUE TITLE
In which directory received mail?

### ISSUE THREAD

**Issue by lixwlixw** [ONLYOFFICE/Docker-MailServer#5]
Taking no reply mail on email server
In which directory received mail?

Use E-mail client?(without password)

**Comment by AlexeySafronov** [comment]
> In which directory received mail?

/var/vmail/

> Use E-mail client?(without password)

This mail server is used as an add-on to ONLYOFFICE/Docker-CommunityServer.
Passwords are generated automatically.
Supports only ONLYOFFICE E-mail client.
